#!/bin/bash
set -o errexit
export REACT_APP_DRAWING_APP_FRONTEND_URL=$DRAWING_APP_FRONTEND_URL
export REACT_APP_DRAWING_APP_BACKEND_URL=$DRAWING_APP_BACKEND_URL
export REACT_APP_MONGODB_URI=$MONGODB_URI
export REACT_APP_MONGODB_DBNAME=$MONGODB_DBNAME
npm install && npm run build